version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=koala
      - MYSQL_USER=koala
      - MYSQL_ROOT_PASSWORD=password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    volumes:
      - /mnt/mysql:/var/lib/mysql
  apiserver:
    image: chengtian/koala-apiserver:v0.1.0
    restart: always
    volumes:
    - $HOME/koala/hack/docker:/etc/koala
    - $HOME/koala/hack:/etc/mail
    command:
    - start
    - "-c=/etc/koala/koala.json"
    depends_on:
    - db
    ports:
    - "9826:9826"
  ui:
    image: chengtian/koala:v0.1.1
    depends_on:
    - apiserver
    volumes:
    - $HOME/koala/hack/docker/ui.conf:/etc/nginx/conf.d/default.conf
    restart: always
    expose:
    - "80"
    - "443"
    ports:
    - "80:80"
    - "443:443"