name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build frontend code
      run: pwd
    - name: Build the Docker image
      run: docker build . --file Dockerfile.ui --tag chengtian/koala:$(date +%s)
